# Generated by Django 5.2.5 on 2025-09-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artists", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artistportfolio",
            name="base_rate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
