# Generated by Django 5.2.5 on 2025-09-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artists", "0002_alter_artistportfolio_base_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artistportfolio",
            name="bio",
            field=models.TextField(default=""),
        ),
    ]
