# Generated by Django 5.2.5 on 2025-09-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="managerprofile",
            name="business_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="managerprofile",
            name="business_license",
            field=models.FileField(blank=True, null=True, upload_to="licenses/"),
        ),
        migrations.AddField(
            model_name="managerprofile",
            name="business_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="managerprofile",
            name="client_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of artists currently managed"
            ),
        ),
        migrations.AddField(
            model_name="managerprofile",
            name="references",
            field=models.TextField(blank=True, help_text="Professional references"),
        ),
        migrations.AddField(
            model_name="managerprofile",
            name="verification_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="managerprofile",
            name="verification_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="managerprofile",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("artist", "Artist"),
                    ("venue", "Venue"),
                    ("manager", "Manager"),
                ],
                help_text="Type of user account",
                max_length=20,
                null=True,
            ),
        ),
    ]
