# Generated by Django 5.2.5 on 2025-01-27 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('concert', 'Concert'), ('wedding', 'Wedding'), ('corporate', 'Corporate Event'), ('festival', 'Festival'), ('private_party', 'Private Party'), ('club_gig', 'Club Gig'), ('theater', 'Theater Performance'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('venue_name', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('setup_time', models.TimeField(blank=True, null=True)),
                ('expected_attendance', models.PositiveIntegerField()),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('budget_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_terms', models.TextField(blank=True)),
                ('technical_requirements', models.TextField(blank=True)),
                ('equipment_provided', models.TextField(blank=True)),
                ('equipment_needed', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venue', models.ForeignKey(limit_choices_to={'user_type': 'venue'}, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('proposed_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('special_requirements', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(limit_choices_to={'user_type': 'artist'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='bookings.event')),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'booking request',
                'verbose_name_plural': 'booking requests',
                'ordering': ['-created_at'],
                'unique_together': {('event', 'artist')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('final_payment_paid', models.BooleanField(default=False)),
                ('performance_duration', models.DurationField()),
                ('set_list', models.TextField(blank=True)),
                ('special_requirements', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='confirmed', max_length=20)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_bookings', to=settings.AUTH_USER_MODEL)),
                ('booking_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='bookings.bookingrequest')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.event')),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_bookings', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('standard', 'Standard Contract'), ('custom', 'Custom Contract')], default='standard', max_length=20)),
                ('terms_and_conditions', models.TextField()),
                ('special_clauses', models.TextField(blank=True)),
                ('artist_signed', models.BooleanField(default=False)),
                ('venue_signed', models.BooleanField(default=False)),
                ('manager_signed', models.BooleanField(default=False)),
                ('artist_signature_date', models.DateTimeField(blank=True, null=True)),
                ('venue_signature_date', models.DateTimeField(blank=True, null=True)),
                ('manager_signature_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_signature', 'Pending Signature'), ('signed', 'Signed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'contract',
                'verbose_name_plural': 'contracts',
                'ordering': ['-created_at'],
            },
        ),
    ]
