# Generated by Django 5.2.5 on 2025-09-01 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0002_alter_booking_manager"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingrequest",
            name="audience_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="budget",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="duration",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="event_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="event_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="event_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="event_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="requester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="requester_type",
            field=models.CharField(
                blank=True,
                choices=[("venue", "Venue"), ("manager", "Manager")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="venue_location",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_requests",
                to="bookings.event",
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="message",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="proposed_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
